const data = [
  {
    Fabric: "Attic",
    Technique: "Red-figure",
    "Artifact Type": "Kylix",
    Date: "-550 to -530",
    Description: "Intricately detailed scene of a symposium",
    "Attributed To": "Hercules",
  },
  {
    Fabric: "Corinthian",
    Technique: "Black-figure",
    "Artifact Type": "Lekythos",
    Date: "-570 to -550",
    Description: "Graceful depiction of mourning women",
    "Attributed To": "John Cena",
  },
  {
    Fabric: "Laconian",
    Technique: "Black-figure",
    "Artifact Type": "Amphora",
    Date: "-560 to -540",
    Description: "Bold portrayal of ancient Spartan warriors",
    "Attributed To": "Zeus",
  },
  {
    Fabric: "Corinthian",
    Technique: "Black-figure",
    "Artifact Type": "Oinochoe",
    Date: "-575 to -555",
    Description: "Dynamic scene of mythological creatures in combat",
    "Attributed To": "Poseidon",
  },
  {
    Fabric: "Boeotian",
    Technique: "Black-figure",
    "Artifact Type": "Skyphos",
    Date: "-560 to -540",
    Description: "Vibrant depiction of Dionysian revelry",
    "Attributed To": "Artemis",
  },
  {
    Fabric: "Corinthian",
    Technique: "Black-figure",
    "Artifact Type": "Aryballos",
    Date: "-575 to -555",
    Description: "Evocative portrayal of mythological beasts in a hunt",
    "Attributed To": "Apollo",
  },
  {
    Fabric: "Attic",
    Technique: "Black-figure",
    "Artifact Type": "Hydria",
    Date: "-560 to -540",
    Description: "Detailed depiction of a wedding procession",
    "Attributed To": "Hera",
  },
  {
    Fabric: "Corinthian",
    Technique: "Black-figure",
    "Artifact Type": "Pyxis",
    Date: "-570 to -550",
    Description: "Elaborate scene of mythical creatures frolicking in a garden",
    "Attributed To": "Hermes",
  },
  {
    Fabric: "Attic",
    Technique: "Red-figure",
    "Artifact Type": "Krater",
    Date: "-560 to -540",
    Description: "Captivating depiction of a battle between gods and titans",
    "Attributed To": "John Cena",
  },
];


export default data;
